//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stok
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSatıs
    {
        public int SatısId { get; set; }
        public string Barkod { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> GelisFiyat { get; set; }
        public Nullable<int> SatısFiyat { get; set; }
        public string Cinsi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Odeme { get; set; }
    }
}
